[package]
name = "gc-lite"
version = "0.6.2"
edition = "2024"
authors = ["John Ray <996351336@qq.com>"]
description = "A simple partitioned garbage collector"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/nupha/gc-lite"
keywords = ["gc", "memory"]

[features]
gc_arena = []
default = ["gc_arena"]

[dependencies]
gc-lite-macros = { version = "0.2.0", path = "gc-lite-macros" }
bitflags = "2.0"
smallvec = "1.15"
log = "0.4"
