[package]
name = "gc-lite-macros"
version = "0.2.1"
edition = "2024"
authors = ["John Ray <996351336@qq.com>"]
description = "Procedural macros for the gc-lite garbage collector"
license = "Apache-2.0"
repository = "https://github.com/nupha/gc-lite"
keywords = ["gc", "memory"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
